Feature/supportme section
rishavanand/github-profilinator pull request #44
Opened 2020-10-07 17:12 UTC by smkamranqadri

FIxed #20 

![](https://user-images.githubusercontent.com/13115396/95357321-2668d380-08e1-11eb-8fb4-68d61055bd85.png)

![](https://user-images.githubusercontent.com/13115396/95363055-6089a380-08e8-11eb-8eac-91a598db3501.png)

2020-10-07 17:53 UTC, smkamranqadri commented
@rohanprasadofficial @rishavanand something wrong with build?

2020-10-07 18:24 UTC, rishavanand requested changes
The build error is weird, it says there is a double instance of `const { TextArea } = Input;` in `index.tsx` but I see only one. Maybe another build will fix it. 
Btw great work 🎉 , just a few more changes.

2020-10-07 18:24 UTC, rishavanand commented on src/components/Field/SupportMeToField.tsx
> +                    src="https://img.shields.io/badge/Donate-PayPal-green.svg"
Please use `&style=flat-square` to match with other shield design
also, use the `blue` color of PayPal to make it match the brand color.

2020-10-07 18:24 UTC, rishavanand commented on src/components/Field/SupportMeToField.tsx
> +                    src="https://img.shields.io/badge/Donate-Buy%20Me%20A%20Coffee-yellow.svg"
Please use `&style=flat-square` to match with other shield design
also, use the `orange` color of BuyMeACoffee to make it match the brand color.

2020-10-07 18:24 UTC, rishavanand commented on src/config/demo.ts
> +                    data: { paypal: 'logarithm4', buymeacoffee: 'rishavanand' },
Please make the PayPal link empty, `paypal: ''`

2020-10-08 03:55 UTC, rishavanand commented on src/components/Field/SupportMeToField.tsx
> +                    src="https://img.shields.io/badge/Donate-PayPal-green.svg"
You missed the blue color instead of green.

2020-10-08 03:56 UTC, rishavanand commented on src/components/Field/SupportMeToField.tsx
> +                    src="https://img.shields.io/badge/Donate-Buy%20Me%20A%20Coffee-yellow.svg"
You missed the orange color instead of yellow.

2020-10-08 03:58 UTC, rishavanand commented
Hey @smkamranqadri, please fix the colors and then we'll be good to merge.

2020-10-08 10:43 UTC, smkamranqadri commented
![Uploading Screenshot 2020-10-08 at 3.43.15 PM.png…]()

2020-10-08 14:06 UTC, rishavanand approved these changes
LGTM! 🎉 Thanks a lot.

2020-10-08 14:06 UTC, merged

2020-10-17 16:11 UTC, rohanprasadofficial commented
Good job @smkamranqadri  !

2020-10-17 16:28 UTC, smkamranqadri commented
Any priority from the issues, I'll be picking up next one?

2020-10-21 20:13 UTC, rishavanand commented
@smkamranqadri not a priority but saving/reusing config (#52) is next in line.